const sentences =  [
    "The", "Moon", "is", "Beautiful", "isn’t", "it",
    "As", "long", "as", "I", "have", "you", "in", "my", "life,", "I’ll", "be", "okay",
    "You", "have", "the", "key", "to", "my", "heart",
    "I", "want", "you", "to", "be", "my", "valentine", "every", "Valentine’s", "Day",
    "I’m", "yours",
    "I’ve", "never", "felt", "this", "way", "about", "someone", "before",
    "You", "make", "my", "heart", "flutter",
    "You’ve", "stolen", "a", "pizza", "my", "heart",
    "Let’s", "grow", "old", "and", "wrinkly", "together",
    "You", "brighten", "up", "my", "life",
    "You’ve", "got", "me", "smitten",
    "I", "have", "hella", "feelings", "for", "you",
    "I’ve", "always", "got", "your", "back",
    "You", "are", "the", "sunshine", "in", "my", "day", "and", "the", "moonlight", "of", "my", "nights",
    "You", "are", "the", "only", "one", "on", "my", "mind",
    "You’re", "all", "that", "I", "need",
    "I’m", "so", "glad", "you’re", "in", "my", "life",
    "You", "make", "my", "heart", "happy",
    "You", "rock", "my", "boat",
    "You", "made", "me", "believe", "that", "love", "is", "possible",
    "You", "mean", "the", "world", "to", "me",
    "My", "day", "starts", "with", "you", "and", "ends", "with", "you",
    "My", "heart", "calls", "out", "for", "you",
    "I", "could", "search", "my", "whole", "life", "through", "and", "through", "and", "never", "find", "another", "you",
    "Being", "with", "you", "is", "like", "a", "dream", "come", "true"
  ];
  
  let german = {
    "The": "Die",
    "Moon": "Mond",
    "is": "ist",
    "Beautiful": "Schön",
    "isn’t": "ist nicht",
    "it": "es",
    "As": "Wie",
    "long": "lang",
    "as": "wie",
    "I": "Ich",
    "have": "habe",
    "you": "dir",
    "in": "in",
    "my": "mein",
    "life,": "Leben,",
    "I’ll": "Ich werde",
    "be": "sein",
    "okay": "in Ordnung",
    "You": "Du",
    "the": "die",
    "key": "Schlüssel",
    "to": "für",
    "heart": "Herz",
    "want": "möchte",
    "valentine": "Valentin",
    "every": "jeden",
    "Valentine’s": "Valentinstag",
    "Day": "Tag",
    "I’m": "Ich bin",
    "yours": "dein",
    "Deutsch": "Deutsch",
    "I’ve": "Ich habe",
    "never": "nie",
    "felt": "gefühlt",
    "this": "dieses",
    "way": "Art",
    "about": "über",
    "someone": "jemanden",
    "before": "vorher",
    "make": "machst",
    "flutter": "flattern",
    "You’ve": "Du hast",
    "stolen": "gestohlen",
    "a": "eine",
    "pizza": "Pizza",
    "English": "Englisch",
    "Pусский": "Pусский",
    "Let’s": "Lass uns",
    "grow": "wachsen",
    "old": "alt",
    "and": "und",
    "wrinkly": "runzelig",
    "together": "zusammen",
    "brighten": "erhellen",
    "up": "auf",
    "life": "Leben",
    "got": "bekommen",
    "me": "mich",
    "smitten": "verzaubert",
    "hella": "viele",
    "feelings": "Gefühle",
    "always": "immer",
    "your": "deinen",
    "back": "Rücken",
    "are": "bist",
    "sunshine": "Sonnenschein",
    "moonlight": "Mondlicht",
    "of": "von",
    "nights": "Nächte",
    "only": "nur",
    "mind": "Verstand",
    "You’re": "Du bist",
    "all": "alles",
    "that": "dass",
    "need": "brauche",
    "español": "español",
    "so": "so",
    "glad": "glücklich",
    "you’re": "du bist",
    "Hrvatski": "Hrvatski",
    "rock": "rockst",
    "boat": "Boot",
    "made": "gemacht",
    "believe": "glauben",
    "love": "Liebe",
    "possible": "möglich",
    "mean": "bedeuten",
    "world": "Welt",
    "Français": "Français",
    "My": "Mein",
    "starts": "beginnt",
    "with": "mit",
    "ends": "endet",
    "calls": "ruft",
    "out": "aus",
    "could": "könnte",
    "search": "suchen",
    "whole": "ganzes",
    "through": "durch",
    "find": "finden",
    "another": "einen anderen",
    "Being": "Das Sein",
    "dream": "Traum",
    "come": "kommen",
    "true": "wahr"
  }
  let spanish =
  {
    "The": "El",
    "Moon": "Luna",
    "is": "es",
    "Beautiful": "Hermoso",
    "isn’t": "no es",
    "it": "eso",
    "As": "Como",
    "long": "largo",
    "as": "como",
    "I": "Yo",
    "have": "tengo",
    "you": "tú",
    "in": "en",
    "my": "mi",
    "life,": "vida,",
    "I’ll": "Voy a",
    "be": "ser",
    "okay": "bien",
    "You": "Tú",
    "the": "el",
    "key": "llave",
    "to": "para",
    "heart": "corazón",
    "want": "quiero",
    "valentine": "Valentín",
    "every": "cada",
    "Valentine’s": "Día de San Valentín",
    "Day": "Día",
    "I’m": "Yo estoy",
    "yours": "tuyo",
    "Deutsch": "Alemán",
    "I’ve": "Yo he",
    "never": "nunca",
    "felt": "sentido",
    "this": "esto",
    "way": "camino",
    "about": "acerca de",
    "someone": "alguien",
    "before": "antes",
    "make": "haces",
    "flutter": "revolotear",
    "You’ve": "Tú has",
    "stolen": "robado",
    "a": "una",
    "pizza": "Pizza",
    "English": "Inglés",
    "Pусский": "Ruso",
    "Let’s": "Vamos a",
    "grow": "crecer",
    "old": "viejo",
    "and": "y",
    "wrinkly": "arrugado",
    "together": "juntos",
    "brighten": "iluminar",
    "up": "arriba",
    "life": "vida",
    "got": "obtenido",
    "me": "a mí",
    "smitten": "enamorado",
    "hella": "muchos",
    "feelings": "sentimientos",
    "always": "siempre",
    "your": "tu",
    "back": "espalda",
    "are": "eres",
    "sunshine": "sol",
    "moonlight": "luz de luna",
    "of": "de",
    "nights": "noches",
    "only": "solo",
    "mind": "mente",
    "You’re": "Tú eres",
    "all": "todo",
    "that": "eso",
    "need": "necesito",
    "español": "español",
    "so": "tan",
    "glad": "feliz",
    "you’re": "tú eres",
    "Hrvatski": "Croata",
    "rock": "mueves",
    "boat": "barco",
    "made": "hecho",
    "believe": "creer",
    "love": "amor",
    "possible": "posible",
    "mean": "significar",
    "world": "mundo",
    "Français": "Francés",
    "My": "Mi",
    "starts": "comienza",
    "with": "con",
    "ends": "termina",
    "calls": "llama",
    "out": "fuera",
    "could": "podría",
    "search": "buscar",
    "whole": "todo",
    "through": "a través de",
    "find": "encontrar",
    "another": "otro",
    "Being": "Siendo",
    "dream": "sueño",
    "come": "venir",
    "true": "verdadero"
    }
    
    
  
    let french = {
      "The": "Le",
      "Moon": "Lune",
      "is": "est",
      "Beautiful": "Beau",
      "isn’t": "n'est pas",
      "it": "il",
      "As": "Comme",
      "long": "long",
      "as": "que",
      "I": "Je",
      "have": "ai",
      "you": "toi",
      "in": "dans",
      "my": "mon",
      "life,": "vie,",
      "I’ll": "Je vais",
      "be": "être",
      "okay": "d'accord",
      "You": "Tu",
      "the": "la",
      "key": "clé",
      "to": "pour",
      "heart": "cœur",
      "want": "veux",
      "valentine": "Valentin",
      "every": "chaque",
      "Valentine’s": "Jour de la Saint-Valentin",
      "Day": "Jour",
      "I’m": "Je suis",
      "yours": "tien",
      "Deutsch": "Allemand",
      "I’ve": "J'ai",
      "never": "jamais",
      "felt": "ressenti",
      "this": "ce",
      "way": "chemin",
      "about": "à propos de",
      "someone": "quelqu'un",
      "before": "avant",
      "make": "fais",
      "flutter": "voltiger",
      "You’ve": "Tu as",
      "stolen": "volé",
      "a": "une",
      "pizza": "pizza",
      "English": "Anglais",
      "Pусский": "Russe",
      "Let’s": "Laisse-nous",
      "grow": "grandir",
      "old": "vieux",
      "and": "et",
      "wrinkly": "ridé",
      "together": "ensemble",
      "brighten": "illuminer",
      "up": "haut",
      "life": "vie",
      "got": "obtenu",
      "me": "moi",
      "smitten": "épris",
      "hella": "beaucoup",
      "feelings": "sentiments",
      "always": "toujours",
      "your": "ton",
      "back": "dos",
      "are": "es",
      "sunshine": "soleil",
      "moonlight": "clair de lune",
      "of": "de",
      "nights": "nuits",
      "only": "seulement",
      "mind": "esprit",
      "You’re": "Tu es",
      "all": "tout",
      "that": "que",
      "need": "besoin",
      "español": "espagnol",
      "so": "tellement",
      "glad": "heureux",
      "you’re": "tu es",
      "Hrvatski": "Croate",
      "rock": "balancer",
      "boat": "bateau",
      "made": "fait",
      "believe": "croire",
      "love": "amour",
      "possible": "possible",
      "mean": "signifier",
      "world": "monde",
      "Français": "Français",
      "My": "Mon",
      "starts": "commence",
      "with": "avec",
      "ends": "se termine",
      "calls": "appelle",
      "out": "dehors",
      "could": "pourrait",
      "search": "chercher",
      "whole": "tout",
      "through": "à travers",
      "find": "trouver",
      "another": "un autre",
      "Being": "Être",
      "dream": "rêve",
      "come": "venir",
      "true": "vrai"
      }
    
      let russian = {
        "The": "Да",
        "Moon": "Луна",
        "is": "это",
        "Beautiful": "Прекрасно",
        "isn’t": "не",
        "it": "это",
        "As": "Как",
        "long": "долго",
        "as": "как",
        "I": "Я",
        "have": "иметь",
        "you": "вы",
        "in": "в",
        "my": "мои",
        "life,": "жизни,",
        "I’ll": "Я буду",
        "be": "быть",
        "okay": "хорошо",
        "You": "Ты",
        "the": "ключ",
        "key": "к",
        "to": "к",
        "heart": "сердцу",
        "want": "хочу",
        "valentine": "валентин",
        "every": "каждый",
        "Valentine’s": "День святого Валентина",
        "Day": "День",
        "I’m": "Я",
        "yours": "твой",
        "Deutsch": "Немецкий",
        "I’ve": "У меня есть",
        "never": "никогда",
        "felt": "чувствовал",
        "this": "это",
        "way": "путь",
        "about": "о",
        "someone": "кто-то",
        "before": "до",
        "make": "делай",
        "flutter": "трепетать",
        "You’ve": "У тебя есть",
        "stolen": "украдено",
        "a": "один",
        "pizza": "пицца",
        "English": "Английский",
        "Pусский": "Русский",
        "Let’s": "Давайте",
        "grow": "расти",
        "old": "старый",
        "and": "и",
        "wrinkly": "морщинистый",
        "together": "вместе",
        "brighten": "освежить",
        "up": "вверх",
        "life": "жизнь",
        "got": "получил",
        "me": "меня",
        "smitten": "очарованный",
        "hella": "очень",
        "feelings": "чувства",
        "always": "всегда",
        "your": "твои",
        "back": "спина",
        "are": "есть",
        "sunshine": "солнце",
        "moonlight": "лунный свет",
        "of": "из",
        "nights": "ночей",
        "only": "только",
        "mind": "разум",
        "You’re": "Ты",
        "all": "все",
        "that": "что",
        "need": "нуждаются",
        "español": "испанский",
        "so": "так",
        "glad": "рад",
        "you’re": "ты",
        "Hrvatski": "Хорватский",
        "rock": "колыбель",
        "boat": "лодка",
        "made": "сделано",
        "believe": "поверь",
        "love": "любовь",
        "possible": "возможно",
        "mean": "означает",
        "world": "мир",
        "Français": "Французский",
        "My": "Мой",
        "starts": "начинается",
        "with": "с",
        "ends": "заканчивается",
        "calls": "зовет",
        "out": "вне",
        "could": "мог",
        "search": "искать",
        "whole": "весь",
        "through": "через",
        "find": "найти",
        "another": "другой",
        "Being": "Бытие",
        "dream": "мечта",
        "come": "приходит",
        "true": "правда"
        }
  
        let hrvatski = {
          "The": "O",
          "Moon": "Mjesec",
          "is": "je",
          "Beautiful": "Predivan",
          "isn’t": "nije",
          "it": "to",
          "As": "Kao",
          "long": "dugo",
          "as": "kao",
          "I": "Ja",
          "have": "imam",
          "you": "tebe",
          "in": "u",
          "my": "moj",
          "life,": "životu,",
          "I’ll": "Ja ću",
          "be": "biti",
          "okay": "u redu",
          "You": "Ti",
          "the": "ključ",
          "key": "za",
          "to": "za",
          "heart": "srce",
          "want": "želim",
          "valentine": "Valentinovo",
          "every": "svaki",
          "Valentine’s": "Valentinovo",
          "Day": "dan",
          "I’m": "Ja sam",
          "yours": "tvoj",
          "Deutsch": "Njemački",
          "I’ve": "Imam",
          "never": "nikad",
          "felt": "osjećao",
          "this": "ovako",
          "way": "put",
          "about": "o",
          "someone": "nekom",
          "before": "prije",
          "make": "napravi",
          "flutter": "leteći",
          "You’ve": "Imaš",
          "stolen": "ukrao",
          "a": "jednu",
          "pizza": "picu",
          "English": "Engleski",
          "Pусский": "Ruski",
          "Let’s": "Hajmo",
          "grow": "rasti",
          "old": "star",
          "and": "i",
          "wrinkly": "boran",
          "together": "zajedno",
          "brighten": "osvijetli",
          "up": "gore",
          "life": "život",
          "got": "dobio",
          "me": "mene",
          "smitten": "zaslijepljen",
          "hella": "pun",
          "feelings": "osjećaji",
          "always": "uvijek",
          "your": "tvoj",
          "back": "leđa",
          "are": "si",
          "sunshine": "sunčev svjetlost",
          "moonlight": "mjesečina",
          "of": "od",
          "nights": "noći",
          "only": "samo",
          "mind": "um",
          "You’re": "Ti si",
          "all": "sve",
          "that": "što",
          "need": "potrebno",
          "español": "španjolski",
          "so": "tako",
          "glad": "sretan",
          "you’re": "ti si",
          "Hrvatski": "Hrvatski",
          "rock": "ljuljati",
          "boat": "brod",
          "made": "napravljeno",
          "believe": "vjerovati",
          "love": "ljubav",
          "possible": "moguće",
          "mean": "značiti",
          "world": "svijet",
          "Français": "Francuski",
          "My": "Moj",
          "starts": "počinje",
          "with": "s",
          "ends": "završava",
          "calls": "zove",
          "out": "van",
          "could": "mogao",
          "search": "tražiti",
          "whole": "cijelo",
          "through": "kroz",
          "find": "nađi",
          "another": "drugi",
          "Being": "Bivanje",
          "dream": "san",
          "come": "doći",
          "true": "istinit"
          }